psychsys-backend/appointment/urls.py
# urls.py
# Path: appointment/urls.py

"""
Author: Adams Pierre David
Since: 1.0.0
"""

from django.urls import include, path

from appointment.views import (
    appointment_client_information, appointment_request, appointment_request_submit, confirm_reschedule,
    default_thank_you, enter_verification_code, get_available_slots_ajax, get_next_available_date_ajax,
    get_non_working_days_ajax, prepare_reschedule_appointment, reschedule_appointment_submit, set_passwd,
    send_verification_code, confirm_verification_code
)
from appointment.views_admin import (
    add_day_off, add_or_update_service, add_or_update_staff_info, add_staff_member_info, add_working_hours,
    create_new_staff_member, delete_appointment, delete_appointment_ajax, delete_day_off, delete_service,
    delete_working_hours, display_appointment, email_change_verification_code, fetch_service_list_for_staff,
    fetch_staff_list, get_service_list, get_user_appointments, is_user_staff_admin, make_superuser_staff_member,
    remove_staff_member, remove_superuser_staff_member, update_appt_date_time, update_appt_min_info, update_day_off,
    update_personal_info, update_working_hours, user_profile, validate_appointment_date
)
prefix = 'api/'
prefix_admin = ''
app_name = 'appointment'

admin_urlpatterns = [
    # display the calendar with the events
    path(f'{prefix_admin}appointments/<str:response_type>/', get_user_appointments, name='get_user_event_type'),
    path(f'{prefix_admin}appointments/', get_user_appointments, name='get_user_appointments'),

    # create a new staff member and make/remove superuser staff member
    path(f'{prefix_admin}add-staff-member-info/', add_staff_member_info, name='add_staff_member_info'),
    path(f'{prefix_admin}create-new-staff-member/', create_new_staff_member, name='add_staff_member_personal_info'),
    path(f'{prefix_admin}update-staff-member/<int:user_id>/', add_or_update_staff_info, name='update_staff_other_info'),
    path(f'{prefix_admin}add-staff-member/', add_or_update_staff_info, name='add_staff_other_info'),
    path(f'{prefix_admin}make-superuser-staff-member/', make_superuser_staff_member, name='make_superuser_staff_member'),
    path(f'{prefix_admin}remove-superuser-staff-member/', remove_superuser_staff_member, name='remove_superuser_staff_member'),

    # remove staff member
    path(f'{prefix_admin}remove-staff-member/<int:staff_user_id>/', remove_staff_member, name='remove_staff_member'),

    # add, update, remove services
    path(f'{prefix_admin}add-service/', add_or_update_service, name='add_service'),
    path(f'{prefix_admin}update-service/<int:service_id>/', add_or_update_service, name='update_service'),
    path(f'{prefix_admin}delete-service/<int:service_id>/', delete_service, name='delete_service'),
    path(f'{prefix_admin}service-list/', get_service_list, name='get_service_list'),
    path(f'{prefix_admin}service-list/<str:response_type>/', get_service_list, name='get_service_list_type'),
    path(f'{prefix_admin}view-service/<int:service_id>/<int:view>/', add_or_update_service, name='view_service'),

    # display details for one event
    path(f'{prefix_admin}display-appointment/<int:appointment_id>/', display_appointment, name='display_appointment'),

    # complete profile
    path(f'{prefix_admin}user-profile/<int:staff_user_id>/', user_profile, name='user_profile'),
    path(f'{prefix_admin}user-profile/', user_profile, name='user_profile'),
    path(f'{prefix_admin}update-user-info/<int:staff_user_id>/', update_personal_info, name='update_user_info'),
    path(f'{prefix_admin}update-user-info/', update_personal_info, name='update_user_info'),

    # add, update, delete day off with staff_user_id
    path(f'{prefix_admin}add-day-off/<int:staff_user_id>/', add_day_off, name='add_day_off'),
    path(f'{prefix_admin}update-day-off/<int:day_off_id>/<int:staff_user_id>/', update_day_off, name='update_day_off_id'),
    path(f'{prefix_admin}delete-day-off/<int:day_off_id>/<int:staff_user_id>/', delete_day_off, name='delete_day_off_id'),

    # add, update, delete day off without staff_user_id
    path(f'{prefix_admin}update-day-off/<int:day_off_id>/', update_day_off, name='update_day_off'),
    path(f'{prefix_admin}delete-day-off/<int:day_off_id>/', delete_day_off, name='delete_day_off'),

    # add, update, delete working hours with staff_user_id
    path(f'{prefix_admin}update-working-hours/<int:working_hours_id>/<int:staff_user_id>/', update_working_hours,
         name='update_working_hours_id'),
    path(f'{prefix_admin}add-working-hours/<int:staff_user_id>/', add_working_hours, name='add_working_hours_id'),
    path(f'{prefix_admin}delete-working-hours/<int:working_hours_id>/<int:staff_user_id>/', delete_working_hours,
         name='delete_working_hours_id'),

    # add, update, delete working hours without staff_user_id
    path(f'{prefix_admin}update-working-hours/<int:working_hours_id>/', update_working_hours, name='update_working_hours'),
    path(f'{prefix_admin}add-working-hours/', add_working_hours, name='add_working_hours'),
    path(f'{prefix_admin}delete-working-hours/<int:working_hours_id>/', delete_working_hours, name='delete_working_hours'),

    # delete appointment
    path(f'{prefix_admin}delete-appointment/<int:appointment_id>/', delete_appointment, name='delete_appointment'),
]

ajax_urlpatterns = [
    path(f'{prefix}available_slots/', get_available_slots_ajax, name='available_slots_ajax'),
    path(f'{prefix}request_next_available_slot/<int:service_id>/', get_next_available_date_ajax,
         name='request_next_available_slot'),
    path(f'{prefix}request_staff_info/', get_non_working_days_ajax, name='get_non_working_days_ajax'),
    path(f'{prefix}fetch_service_list_for_staff/', fetch_service_list_for_staff, name='fetch_service_list_for_staff'),
    path(f'{prefix}fetch_staff_list/', fetch_staff_list, name='fetch_staff_list'),
    path(f'{prefix}update_appt_min_info/', update_appt_min_info, name="update_appt_min_info"),
    path(f'{prefix}update_appt_date_time/', update_appt_date_time, name="update_appt_date_time"),
    path(f'{prefix}validate_appointment_date/', validate_appointment_date, name="validate_appointment_date"),
    # delete appointment ajax
    path(f'{prefix}delete_appointment/', delete_appointment_ajax, name="delete_appointment_ajax"),
    path(f'{prefix}is_user_staff_admin/', is_user_staff_admin, name="is_user_staff_admin"),
]

urlpatterns = [
    # homepage
    path(f'{prefix}request/<int:service_id>/', appointment_request, name='appointment_request'),
    path(f'{prefix}request-submit/', appointment_request_submit, name='appointment_request_submit'),
    path(f'{prefix}appointment/<str:id_request>/reschedule/', prepare_reschedule_appointment,
         name='prepare_reschedule_appointment'),
    path(f'{prefix}appointment-reschedule-submit/', reschedule_appointment_submit, name='reschedule_appointment_submit'),
    path(f'{prefix}confirm-reschedule/<str:id_request>/', confirm_reschedule, name='confirm_reschedule'),
    path(f'{prefix}client-info/<int:appointment_request_id>/<str:id_request>/', appointment_client_information,
         name='appointment_client_information'),
    path(f'{prefix}verification-code/<int:appointment_request_id>/<str:id_request>/', enter_verification_code,
         name='enter_verification_code'),
    path(f'{prefix}verification-code/', email_change_verification_code, name='email_change_verification_code'),
    path(f'{prefix}thank-you/<int:appointment_id>/', default_thank_you, name='default_thank_you'),
    path(f'{prefix}verify/<uidb64>/<str:token>/', set_passwd, name='set_passwd'),
    path(f'{prefix}ajax/', include(ajax_urlpatterns)),
    path(f'{prefix}app-admin/', include(admin_urlpatterns)),
    path(f'{prefix}appointment_api/send_verification_code/', send_verification_code, name='send_verification_code'),
    path(f'{prefix}appointment_api/confirm_verification_code/', confirm_verification_code, name='confirm_verification_code'),
]

psychsys-backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from appointment_reminder.views import get_instagram_images, create_assessment

urlpatterns = [
    path('', include("appointment_reminder.urls")),
    # path('appointments/<str:response_type>/', include('appointment.urls')),
    path('', include('appointment.urls')),
    path('api/admin/', admin.site.urls),
    path('api/get_instagram_images/', get_instagram_images, name='get_instagram_images'),
    path('api/create_assessment/', create_assessment, name='create_assessment'),
]

psychsys-backend/appointment/forms.py
# forms.py
# Path: appointment/forms.py

"""
Author: Adams Pierre David
Since: 1.0.0
"""

from django import forms
from django.utils.translation import gettext as _
from phonenumber_field.formfields import SplitPhoneNumberField

from .models import (
    Appointment, AppointmentRequest, AppointmentRescheduleHistory, DayOff, Service, StaffMember,
    WorkingHours
)
from .utils.db_helpers import get_user_model
from .utils.validators import not_in_the_past


class SlotForm(forms.Form):
    selected_date = forms.DateField(validators=[not_in_the_past])
    staff_member = forms.ModelChoiceField(StaffMember.objects.all(),
                                          error_messages={'invalid_choice': 'Staff member does not exist'})


class AppointmentRequestForm(forms.ModelForm):
    class Meta:
        model = AppointmentRequest
        fields = ('date', 'start_time', 'end_time', 'service', 'staff_member')


class ReschedulingForm(forms.ModelForm):
    class Meta:
        model = AppointmentRescheduleHistory
        fields = ['reason_for_rescheduling']
        widgets = {
            'reason_for_rescheduling': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Reason for rescheduling...'}),
        }


class AppointmentForm(forms.ModelForm):
    phone = SplitPhoneNumberField()

    class Meta:
        model = Appointment
        fields = ('phone', 'want_reminder', 'address', 'additional_info')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs.update(
                {
                    'placeholder': '1234567890'
                })
        self.fields['additional_info'].widget.attrs.update(
                {
                    'rows': 2,
                    'class': 'form-control',
                })
        self.fields['address'].widget.attrs.update(
                {
                    'rows': 2,
                    'class': 'form-control',
                    'placeholder': '1234 Main St, City, State, Zip Code',
                    'required': 'true'
                })
        self.fields['additional_info'].widget.attrs.update(
                {
                    'class': 'form-control',
                    'placeholder': 'I would like to be contacted by phone.'
                })


class ClientDataForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))


class PersonalInformationForm(forms.Form):
    # first_name, last_name, email
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # pop the user from the kwargs
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if self.user:
            if self.user.email == email:
                return email
            queryset = get_user_model().objects.exclude(pk=self.user.pk)
        else:
            queryset = get_user_model().objects.all()

        if queryset.filter(email=email).exists():
            raise forms.ValidationError(_("This email is already taken."))

        return email


class StaffAppointmentInformationForm(forms.ModelForm):
    class Meta:
        model = StaffMember
        fields = ['services_offered', 'slot_duration', 'lead_time', 'finish_time',
                  'appointment_buffer_time', 'work_on_saturday', 'work_on_sunday']
        widgets = {
            'service_offered': forms.Select(attrs={'class': 'form-control'}),
            'slot_duration': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 30, 60, 90, 120... (in minutes)')
            }),
            'lead_time': forms.TimeInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 08:00:00, 09:00:00... (24-hour format)')
            }),
            'finish_time': forms.TimeInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 17:00:00, 18:00:00... (24-hour format)')
            }),
            'appointment_buffer_time': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 15, 30, 45, 60... (in minutes)')
            }),
            'work_on_saturday': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'work_on_sunday': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class StaffMemberForm(forms.ModelForm):
    class Meta:
        model = StaffMember
        fields = ['user', 'services_offered', 'slot_duration', 'lead_time', 'finish_time',
                  'appointment_buffer_time', 'work_on_saturday', 'work_on_sunday']
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'service_offered': forms.Select(attrs={'class': 'form-control'}),
            'slot_duration': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 30, 60, 90, 120... (in minutes)')
            }),
            'lead_time': forms.TimeInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 08:00:00, 09:00:00... (24-hour format)')
            }),
            'finish_time': forms.TimeInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 17:00:00, 18:00:00... (24-hour format)')
            }),
            'appointment_buffer_time': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example value: 15, 30, 45, 60... (in minutes)')
            }),
            'work_on_saturday': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'work_on_sunday': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        super(StaffMemberForm, self).__init__(*args, **kwargs)
        # Exclude users who are already staff members
        existing_staff_user_ids = StaffMember.objects.values_list('user', flat=True)
        # Filter queryset for user field to include only superusers or users not already staff members
        self.fields['user'].queryset = get_user_model().objects.filter(
                is_superuser=True
        ).exclude(id__in=existing_staff_user_ids) | get_user_model().objects.exclude(
                id__in=existing_staff_user_ids
        )


class StaffDaysOffForm(forms.ModelForm):
    class Meta:
        model = DayOff
        fields = ['start_date', 'end_date', 'description']
        widgets = {
            'start_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'end_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class StaffWorkingHoursForm(forms.ModelForm):
    class Meta:
        model = WorkingHours
        fields = ['day_of_week', 'start_time', 'end_time']


class ServiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['background_color'].widget.attrs['value'] = self.instance.background_color

    class Meta:
        model = Service
        fields = ['name', 'description', 'duration', 'price', 'down_payment', 'image', 'currency', 'background_color']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Example: First Consultation')
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': "Example: Overview of client's needs."
            }),
            'duration': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'HH:MM:SS, (example: 00:15:00 for 15 minutes)'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Example: 100.00 (0 for free)'
            }),
            'down_payment': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Example: 50.00 (0 for free)'
            }),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'currency': forms.Select(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')],
                                     attrs={'class': 'form-control'}),
            'background_color': forms.TextInput(attrs={'class': 'form-control', 'type': 'color', 'value': '#000000'}),
        }

psychsys-backend/appointment/templates/administration/email_change_verification_code.html
{% extends BASE_TEMPLATE %}
{% load i18n %}
{% load static %}
{% block customCSS %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/verification_code.css' %}"/>
{% endblock %}
{% block title %}
    {% trans 'Enter Verification Code' %}
{% endblock %}
{% block description %}
    {% trans 'Enter Verification Code' %}
{% endblock %}
{% block body %}
    <section class="content content-wrapper">
        <div class="main-container">
            <div class="body-container">
                <h1>{% trans 'Enter Verification Code' %}</h1>
                <p>{% trans "We've sent a verification code to your email. Please enter it below" %}:</p>
                <form method="post"
                      action="{% url 'appointment:email_change_verification_code' %}">
                    {% csrf_token %}
                    <label>{% trans 'Code' %}:
                        <input type="text" name="code" placeholder="X1Y2Z3" required>
                    </label>
                    <button class="btn btn-primary" type="submit">{% trans 'Submit' %}</button>
                </form>
            </div>
        </div>
        <div class="messages" style="margin: 20px 0">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-dismissible {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
                         role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}
{% block customJS %}
    <script src="{% static 'js/js-utils.js' %}"></script>
{% endblock %}

psychsys-backend/appointment/templates/administration/manage_service.html
{% extends BASE_TEMPLATE %}
{% load i18n %}
{% load static %}

{% block customCSS %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/btn.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/service.css' %}"/>
{% endblock %}

{% block body %}
    <section class="content content-wrapper">
        <div class="service-form-wrapper">
            <div class="service-form-content">
                <h2>{{ page_title }}</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if btn_text %}
                        <button type="submit" class="btn btn-primary">{{ btn_text }}</button>
                    {% else %}
                        {% if request.user.is_superuser and service.id %}
                            <div class="service-btn-container">
                                <a href="{% url 'appointment:update_service' service_id=service.id %}"
                                   class="modify-btn button-color-blue service-btn">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="javascript:void(0)"
                                   onclick="showModal('{{ modal_title }}', '{{ d_modal_message }}', '{{ delete_btn_modal }}', '{% url 'appointment:delete_service' service_id=service.id %}', null)"
                                   class="modify-btn button-color-red service-btn">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        {% endif %}
                    {% endif %}
                </form>
                <div class="messages" style="margin: 20px 0">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-dismissible {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
                                 role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block customJS %}
    <script src="{% static 'js/js-utils.js' %}"></script>
{% endblock %}

psychsys-backend/appointment/templates/administration/service_list.html
{% extends BASE_TEMPLATE %}
{% load i18n %}
{% load static %}
{% block customCSS %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/btn.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/user_profile.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}
{% block title %}
    {% trans 'Service List' %}
{% endblock %}
{% block description %}
    {% trans 'Service List' %}.
{% endblock %}
{% block body %}
    <section class="content content-wrapper">
        <div class="service-container">
            <section class="profile-section">
                <div class="section-header">
                    <h2 class="section-header-itm">{% trans 'Service List' %}</h2>
                </div>
                <div class="responsive-table-container">
                    <table>
                        <thead>
                        <tr>
                            <th>{% trans 'Name' %}</th>
                            <th>{% trans 'Duration' %}</th>
                            <th>{% trans 'Price' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in services %}
                            <tr>
                                <td>{{ service.name }}</td>
                                <td>{{ service.get_duration }}</td>
                                <td>{{ service.get_price_text }}</td>
                                <td>
                                    <div class="buttons-container">
                                        <a href="{% url 'appointment:view_service' service_id=service.id view=1 %}"
                                           class="modify-btn button-color-green">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        {% translate "Are you sure you want to delete this service?" as d_modal_message %}
                                        {% if request.user.is_superuser %}
                                            <a href="{% url 'appointment:update_service' service_id=service.id %}"
                                               class="modify-btn button-color-blue">
                                                <i class="fas fa-pen"></i>
                                            </a>
                                            <a href="javascript:void(0)"
                                               onclick="showModal('{{ modal_title }}', '{{ d_modal_message }}', '{{ delete_btn_modal }}', '{% url 'appointment:delete_service' service_id=service.id %}', null)"
                                               class="modify-btn button-color-red">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">{% trans 'No service found' %}.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
            <div class="messages" style="margin: 20px 0">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-dismissible {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
                             role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

{% block customJS %}
    <script src="{% static 'js/js-utils.js' %}"></script>
{% endblock %}

psychsys-backend/appointment/templates/administration/staff_list.html
{% extends BASE_TEMPLATE %}
{% load i18n %}
{% load static %}
{% block customCSS %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/btn.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_admin/user_profile.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}
{% block title %}
    Staff Members List
{% endblock %}
{% block description %}
    {% trans 'List of all staff members' %}.
{% endblock %}
{% block body %}
    <section class="content content-wrapper">
        <div class="profile-container">
            <section class="profile-section">
                <div class="section-header">
                    <h2 class="section-header-itm">{% trans 'Staff Members' %}</h2>
                    <div class="buttons-container section-header-itm">
                        <a href="{{ btn_staff_me_link }}"
                           class="modify-btn button-color-purple">
                            {{ btn_staff_me }}
                        </a>
                        <a href="{% url 'appointment:add_staff_member_info' %}"
                           class="modify-btn button-color-green">
                            <i class="fas fa-add"></i>
                        </a>
                    </div>
                </div>
                <div class="responsive-table-container">
                    <table>
                        <thead>
                        <tr>
                            <th>{% trans 'Name' %}</th>
                            <th>{% trans 'Email' %}</th>
                            <th>{% trans 'Details' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for staff_member in staff_members %}
                            <tr>
                                <td>{{ staff_member.get_staff_member_name }}</td>
                                <td>{{ staff_member.user.email|default:"N/A" }}</td>
                                <td>
                                    <a href="{% url 'appointment:user_profile' staff_member.user.id %}"
                                       class="modify-btn button-color-blue">{% trans 'View Profile' %}</a>
                                    <a href="{% url 'appointment:remove_staff_member' staff_member.user.id %}"
                                       class="modify-btn button-color-red">{% trans 'Remove' %}</a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">{% trans 'No staff members found' %}.</td>
                            </tr>
                        {% endfor %}
                        <small>
                            {% trans "PS: Remove means, deleting the staff status of the user. The user account is still active." %}
                        </small>
                        </tbody>
                    </table>
                </div>
            </section>
            <div class="messages" style="margin: 20px 0">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-dismissible {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
                             role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

{% block customJS %}
    <script src="{% static 'js/js-utils.js' %}"></script>
{% endblock %}